export const ipc = {
  appBootstrap: 'app:get-bootstrap', appVersion: 'app:get-version', appNavigate: 'app:navigate', settingsGet: 'settings:get', settingsUpdate: 'settings:update',
  workspaceSelect: 'workspace:select-root', workspaceList: 'workspace:list', workspaceOpen: 'workspace:open',
  workspaceTrust: 'workspace:set-trust', workspaceRemove: 'workspace:remove', workspaceChanged: 'workspace:changed',
  projectPreview: 'project:preview', projectCreate: 'project:create', projectImportPreview: 'project:preview-import',
  projectImport: 'project:import', projectList: 'project:list', projectOpen: 'project:open',
  projectRename: 'project:rename', projectRemove: 'project:remove',
  filesTree: 'files:list-tree', filesRead: 'files:read', filesWrite: 'files:write', filesCreate: 'files:create',
  filesRename: 'files:rename', filesRemove: 'files:remove', filesSearch: 'files:search',
  filesCopy: 'files:copy', filesMove: 'files:move',
  snapshotCreate: 'snapshots:create', snapshotList: 'snapshots:list', snapshotPreview: 'snapshots:preview-restore',
  snapshotRestore: 'snapshots:restore', snapshotRemove: 'snapshots:remove',
  toolchainDetect: 'toolchain:detect', toolchainProbe: 'toolchain:probe', toolchainList: 'toolchain:list',
  toolchainBind: 'toolchain:bind', toolchainUnbind: 'toolchain:unbind', toolchainHealth: 'toolchain:health',
  compilerBuild: 'compiler:build',
  cmakeBuild: 'cmake:build', ctestRun: 'ctest:run',
  analysisClangTidy: 'analysis:clang-tidy',
  vscodeOpen: 'vscode:open',
  environmentOpenDownload: 'environment:open-download',
  environmentInstallerStatus: 'environment:installer-status',
  environmentInstall: 'environment:install', environmentInstallTasks: 'environment:install-tasks',
  environmentInstallChanged: 'environment:install-changed',
  languageStatus: 'language:status', languageSync: 'language:sync',
  languageCompletion: 'language:completion', languageHover: 'language:hover',
  languageDefinition: 'language:definition', languageDiagnostics: 'language:diagnostics',
  debugStart: 'debug:start', debugCommand: 'debug:command',
  programRun: 'program:run', programStop: 'program:stop',
  diagnosticsListActive: 'diagnostics:list-active', diagnosticsAcknowledge: 'diagnostics:acknowledge',
  diagnosticsChanged: 'diagnostics:changed',
  conversationsList: 'conversations:list', conversationsCreate: 'conversations:create', conversationsArchive: 'conversations:archive',
  conversationsMessages: 'conversations:messages',
  conversationsAgentSubmit: 'conversations:submit-agent',
  conversationsChanged: 'conversations:changed',
  agentStart: 'agent:start', agentContinue: 'agent:continue', agentGet: 'agent:get', agentList: 'agent:list', agentCancel: 'agent:cancel',
  agentChanged: 'agent:changed', approvalDecide: 'approval:decide',
  petChanged: 'pet:changed',
  petGetState: 'pet:get-state', petUpdateSettings: 'pet:update-settings',
  petShow: 'pet:show', petHide: 'pet:hide', petToggle: 'pet:toggle',
  petMove: 'pet:move', petDrag: 'pet:drag', petDragEnd: 'pet:drag-end', petUndock: 'pet:undock',
  petSetIgnoreMouseEvents: 'pet:set-ignore-mouse-events', petOpenMain: 'pet:open-main',
  petShowContextMenu: 'pet:show-context-menu', petSelectCustomAsset: 'pet:select-custom-asset', petResetCustomAsset: 'pet:reset-custom-asset',
  petRenameCustomAsset: 'pet:rename-custom-asset', petDeleteCustomAsset: 'pet:delete-custom-asset', petActivateCustomAsset: 'pet:activate-custom-asset',
  petHideForOneHour: 'pet:hide-for-one-hour', petCancelHidden: 'pet:cancel-hidden', petToggleFocusMode: 'pet:toggle-focus-mode',
  petToggleLaunchAtLogin: 'pet:toggle-launch-at-login', petChat: 'pet:chat', petQuickChat: 'pet:quick-chat',
  petWindowChanged: 'pet:window-changed',
  screenshotCapture: 'screenshot:capture', screenshotGetPending: 'screenshot:get-pending',
  screenshotSubmit: 'screenshot:submit', screenshotCancel: 'screenshot:cancel', screenshotSubmitted: 'screenshot:submitted',
  learningCatalog: 'learning:catalog', learningKnowledge: 'learning:knowledge', learningUpdateKnowledge: 'learning:update-knowledge',
  learningBackgroundGet: 'learning:background:get', learningBackgroundSave: 'learning:background:save',
  learningErrors: 'learning:errors', learningReviews: 'learning:reviews', learningSummary: 'learning:summary',
  learningPracticeCatalog: 'learning:practice-catalog', learningPracticeSubmit: 'learning:practice-submit',
  learningPracticeCompleteProject: 'learning:practice-complete-project', learningPracticeImportOjScreenshot: 'learning:practice-import-oj-screenshot',
  modelList: 'model:list', modelSave: 'model:save', modelRemove: 'model:remove',
  modelClearKey: 'model:clear-key', modelTest: 'model:test',
  mockDashboard: 'mocks:get-dashboard'
} as const
